name: feed/heal
author: Guccio
api: 4.0.0
version: 1.0.0
main: Guccio\Main

commands:
  heal:
    usage: /heal
    description: Repprenez toute votre vie
    permission: heal.cmd
    permission-message: Vous n'avez pas la permission d'utiliser cette commande.
    aliases:
      - [hl]
  feed:
    usage: /feed
    description: Nourrissez vous
    permission: feed.cmd
    permission-message: Vous n'avez pas la permission d'utiliser cette commande.
    aliases:
      - [fd]

permissions:
  heal.cmd:
    default: op
  feed.cmd:
    default: op